"""Replicate audio model catalogue (music + speech) — v0.8.0."""

from __future__ import annotations

from src.domain import ModelConfig

# (imported from domain.py, not models_config.py, to avoid the circular import that
# occurred when models_config pulled AUDIO_MODELS at the bottom of its body)

MUSIC_2_5 = ModelConfig(
    name="music-2.5",
    display_name="MiniMax Music 2.5",
    model_type="audio",
    replicate_id="minimax/music-2.5",
    supports_text=True,
    supports_image=False,
    requires_text=False,
    provider="replicate",
    provider_model_id="minimax/music-2.5",
    provider_endpoint="versionless",
    workflow_tags=["music"],
    media_roles={
        "lyrics": "Song lyrics",
        "prompt": "Style and mood",
    },
    balanced_params=["lyrics", "prompt"],
    advanced_params=["bitrate", "sample_rate", "audio_format"],
    defaults={
        "prompt": "",
        "bitrate": 256000,
        "sample_rate": 44100,
        "audio_format": "mp3",
    },
    param_constraints={
        "lyrics": {"max": 3500},
        "prompt": {"max": 2000},
    },
    required_one_of=[("lyrics",)],
    param_help={
        "lyrics": "Required. Use [Verse], [Chorus], etc. and \\n for line breaks.",
        "prompt": "Optional style, mood, and scenario (e.g. pop, rainy night).",
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/minimax/music-2.5",
    pricing_notes="~$0.15 per output audio file (Replicate page, 2026-06-04).",
)

STABLE_AUDIO_2_5 = ModelConfig(
    name="stable-audio-2.5",
    display_name="Stable Audio 2.5",
    model_type="audio",
    replicate_id="stability-ai/stable-audio-2.5",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    provider="replicate",
    provider_model_id="stability-ai/stable-audio-2.5",
    provider_endpoint="versionless",
    workflow_tags=["music"],
    media_roles={"prompt": "Music description"},
    balanced_params=["prompt", "duration"],
    advanced_params=["seed", "steps", "cfg_scale"],
    defaults={"duration": 30, "steps": 8, "cfg_scale": 1},
    param_constraints={
        "duration": {"min": 1, "max": 190, "ui_type": "slider"},
        "steps": {"min": 4, "max": 8, "ui_type": "slider"},
        "cfg_scale": {"min": 1, "max": 25, "ui_type": "slider"},
        "seed": {"nullable": True},
    },
    param_help={
        "duration": "Length in seconds (1–190). Longer clips cost more compute.",
        "steps": "More steps can improve quality but take longer.",
        "cfg_scale": "How closely the output follows your prompt.",
    },
    high_impact_params=["duration", "steps"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/stability-ai/stable-audio-2.5",
    pricing_notes="~$0.20 per output file (Replicate page, 2026-06-04).",
)

LYRIA_2 = ModelConfig(
    name="lyria-2",
    display_name="Google Lyria 2",
    model_type="audio",
    replicate_id="google/lyria-2",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    provider="replicate",
    provider_model_id="google/lyria-2",
    provider_endpoint="versionless",
    workflow_tags=["music"],
    media_roles={
        "prompt": "Music description",
        "negative_prompt": "What to avoid",
    },
    balanced_params=["prompt"],
    advanced_params=["seed", "negative_prompt"],
    defaults={},
    param_constraints={"seed": {"nullable": True}},
    param_help={
        "prompt": "Describe the music you want (style, instruments, mood).",
        "negative_prompt": "Optional — sounds or styles to leave out.",
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/google/lyria-2",
    pricing_notes="~$2 per 1000s of output audio (Replicate page, 2026-06-04).",
)

REALTIME_TTS_2 = ModelConfig(
    name="realtime-tts-2",
    display_name="Inworld Realtime TTS 2",
    model_type="audio",
    replicate_id="inworld/realtime-tts-2",
    supports_text=True,
    supports_image=False,
    requires_text=False,
    provider="replicate",
    provider_model_id="inworld/realtime-tts-2",
    provider_endpoint="versionless",
    workflow_tags=["speech"],
    media_roles={
        "text": "Words to speak",
        "voice_id": "Voice",
        "language": "Language",
    },
    balanced_params=["text", "voice_id"],
    advanced_params=[
        "language",
        "speaking_rate",
        "temperature",
        "audio_format",
        "sample_rate",
        "text_normalization",
    ],
    defaults={
        "language": "auto",
        "voice_id": "Ashley",
        "sample_rate": 48000,
        "audio_format": "mp3",
        "temperature": 0,
        "speaking_rate": 0,
        "text_normalization": "auto",
    },
    param_constraints={
        "text": {"max": 2000},
        "temperature": {"min": 0, "max": 2, "ui_type": "slider"},
        "speaking_rate": {"min": 0, "max": 1.5, "ui_type": "slider"},
    },
    required_one_of=[("text",)],
    param_help={
        "text": "Up to 2000 characters. Bracket tags like [happy] steer delivery.",
        "voice_id": "Preset name (e.g. Ashley) or a cloned voice id.",
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/inworld/realtime-tts-2",
    pricing_notes="~$0.035 per 1k input characters (Replicate page, 2026-06-04).",
)

REALTIME_TTS_15_MAX = ModelConfig(
    name="realtime-tts-1.5-max",
    display_name="Inworld Realtime TTS 1.5 Max",
    model_type="audio",
    replicate_id="inworld/realtime-tts-1.5-max",
    supports_text=True,
    supports_image=False,
    requires_text=False,
    provider="replicate",
    provider_model_id="inworld/realtime-tts-1.5-max",
    provider_endpoint="versionless",
    workflow_tags=["speech"],
    media_roles={"text": "Words to speak", "voice_id": "Voice"},
    balanced_params=["text", "voice_id"],
    advanced_params=[
        "speaking_rate",
        "temperature",
        "audio_format",
        "sample_rate",
        "text_normalization",
    ],
    defaults={
        "voice_id": "Ashley",
        "sample_rate": 48000,
        "audio_format": "mp3",
        "temperature": 0,
        "speaking_rate": 0,
        "text_normalization": "auto",
    },
    param_constraints={
        "text": {"max": 2000},
        "temperature": {"min": 0, "max": 2, "ui_type": "slider"},
        "speaking_rate": {"min": 0, "max": 1.5, "ui_type": "slider"},
    },
    required_one_of=[("text",)],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/inworld/realtime-tts-1.5-max",
    pricing_notes="~$0.035 per 1k input characters (Replicate page, 2026-06-04).",
)

SPEECH_28_HD = ModelConfig(
    name="speech-2.8-hd",
    display_name="MiniMax Speech 2.8 HD",
    model_type="audio",
    replicate_id="minimax/speech-2.8-hd",
    supports_text=True,
    supports_image=False,
    requires_text=False,
    provider="replicate",
    provider_model_id="minimax/speech-2.8-hd",
    provider_endpoint="versionless",
    workflow_tags=["speech"],
    media_roles={
        "text": "Words to speak",
        "voice_id": "Voice",
        "emotion": "Delivery style",
    },
    balanced_params=["text", "voice_id"],
    advanced_params=[
        "speed",
        "pitch",
        "volume",
        "emotion",
        "audio_format",
        "bitrate",
        "sample_rate",
        "channel",
        "language_boost",
        "subtitle_enable",
        "english_normalization",
    ],
    defaults={
        "voice_id": "English_Wiselady",
        "speed": 1,
        "pitch": 0,
        "volume": 1,
        "emotion": "auto",
        "audio_format": "mp3",
        "bitrate": 128000,
        "sample_rate": 32000,
        "channel": "mono",
        "language_boost": "None",
        "subtitle_enable": False,
        "english_normalization": False,
    },
    param_constraints={
        "text": {"max": 10000},
        "speed": {"min": 0.5, "max": 2, "ui_type": "slider"},
        "pitch": {"min": -12, "max": 12, "ui_type": "slider"},
        "volume": {"min": 0, "max": 10, "ui_type": "slider"},
    },
    required_one_of=[("text",)],
    high_impact_params=["voice_id", "emotion"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/minimax/speech-2.8-hd",
    pricing_notes="~$0.10 per 1k input tokens (Replicate page, 2026-06-04).",
)

SPEECH_28_TURBO = ModelConfig(
    name="speech-2.8-turbo",
    display_name="MiniMax Speech 2.8 Turbo",
    model_type="audio",
    replicate_id="minimax/speech-2.8-turbo",
    supports_text=True,
    supports_image=False,
    requires_text=False,
    provider="replicate",
    provider_model_id="minimax/speech-2.8-turbo",
    provider_endpoint="versionless",
    workflow_tags=["speech"],
    media_roles={
        "text": "Words to speak",
        "voice_id": "Voice",
        "emotion": "Delivery style",
    },
    balanced_params=["text", "voice_id"],
    advanced_params=[
        "speed",
        "pitch",
        "volume",
        "emotion",
        "audio_format",
        "bitrate",
        "sample_rate",
        "channel",
        "language_boost",
        "subtitle_enable",
        "english_normalization",
    ],
    defaults={
        "voice_id": "English_Wiselady",
        "speed": 1,
        "pitch": 0,
        "volume": 1,
        "emotion": "auto",
        "audio_format": "mp3",
        "bitrate": 128000,
        "sample_rate": 32000,
        "channel": "mono",
        "language_boost": "None",
        "subtitle_enable": False,
        "english_normalization": False,
    },
    param_constraints={
        "text": {"max": 10000},
        "speed": {"min": 0.5, "max": 2, "ui_type": "slider"},
        "pitch": {"min": -12, "max": 12, "ui_type": "slider"},
        "volume": {"min": 0, "max": 10, "ui_type": "slider"},
    },
    required_one_of=[("text",)],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/minimax/speech-2.8-turbo",
    pricing_notes="~$0.06 per 1k input tokens (Replicate page, 2026-06-04).",
)

CHATTERBOX = ModelConfig(
    name="chatterbox",
    display_name="Resemble Chatterbox",
    model_type="audio",
    replicate_id="resemble-ai/chatterbox",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    provider="replicate",
    provider_model_id="resemble-ai/chatterbox",
    provider_endpoint="versionless",
    workflow_tags=["speech"],
    media_roles={"prompt": "Words to speak"},
    balanced_params=["prompt"],
    advanced_params=["seed", "temperature", "cfg_weight", "exaggeration"],
    defaults={"seed": 0, "temperature": 0.8, "cfg_weight": 0.5, "exaggeration": 0.5},
    param_constraints={
        "temperature": {"min": 0.05, "max": 5, "ui_type": "slider"},
        "cfg_weight": {"min": 0.2, "max": 1, "ui_type": "slider"},
        "exaggeration": {"min": 0.25, "max": 2, "ui_type": "slider"},
    },
    param_help={
        "exaggeration": "0.5 is neutral; extreme values can sound unstable.",
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/resemble-ai/chatterbox",
    pricing_notes="~$0.025 per 1k input characters (Replicate page, 2026-06-04).",
)

ELEVENLABS_V3 = ModelConfig(
    name="elevenlabs-v3",
    display_name="ElevenLabs v3",
    model_type="audio",
    replicate_id="elevenlabs/v3",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    provider="replicate",
    provider_model_id="elevenlabs/v3",
    provider_endpoint="versionless",
    workflow_tags=["speech"],
    media_roles={
        "prompt": "Words to speak",
        "voice": "Voice",
        "language_code": "Language",
    },
    balanced_params=["prompt", "voice"],
    advanced_params=[
        "speed",
        "stability",
        "style",
        "similarity_boost",
        "language_code",
        "previous_text",
        "next_text",
    ],
    defaults={
        "voice": "Rachel",
        "speed": 1,
        "stability": 0.5,
        "style": 0,
        "similarity_boost": 0.75,
        "language_code": "en",
        "previous_text": "",
        "next_text": "",
    },
    param_constraints={
        "speed": {"min": 0.7, "max": 1.2, "ui_type": "slider"},
        "stability": {"min": 0, "max": 1, "ui_type": "slider"},
        "style": {"min": 0, "max": 1, "ui_type": "slider"},
        "similarity_boost": {"min": 0, "max": 1, "ui_type": "slider"},
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/elevenlabs/v3",
    pricing_notes="~$0.10 per 1k input characters (Replicate page, 2026-06-04).",
)

MUSIC_MODELS: list[ModelConfig] = [MUSIC_2_5, STABLE_AUDIO_2_5, LYRIA_2]
SPEECH_MODELS: list[ModelConfig] = [
    REALTIME_TTS_2,
    REALTIME_TTS_15_MAX,
    SPEECH_28_HD,
    SPEECH_28_TURBO,
    CHATTERBOX,
    ELEVENLABS_V3,
]
AUDIO_MODELS: list[ModelConfig] = MUSIC_MODELS + SPEECH_MODELS
