"""Replicate image model catalogue."""

# ruff: noqa: E501

from __future__ import annotations

from src.domain import ModelConfig

_IMAGE_TYPES = ["png", "jpg", "jpeg", "webp"]

NANO_BANANA_2 = ModelConfig(
    name="nano-banana-2",
    display_name="Nano Banana 2",
    model_type="image",
    replicate_id="google/nano-banana-2",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="google/nano-banana-2",
    provider_endpoint="versionless",
    provider_category="Fast multimodal editor",
    provider_summary="Google's speed-focused image model for text-to-image, conversational editing, multi-reference fusion (up to 14 images), and readable in-image text. Best for high-volume iteration and edits without Pro-tier cost.",
    strength_tags=['fast', 'editing', 'multi-reference', 'typography', 'search-grounding'],
    workflow_tags=['text_to_image', 'image_edit', 'typography'],
    media_roles={'prompt': 'Prompt', 'image_input': 'Reference images'},
    balanced_params=['prompt', 'image_input', 'aspect_ratio', 'resolution'],
    advanced_params=['google_search', 'image_search', 'output_format'],
    defaults={'aspect_ratio': '1:1', 'resolution': '1K', 'google_search': False, 'image_search': False, 'output_format': 'jpg'},
    param_constraints={'aspect_ratio': {'enum': ['match_input_image', '1:1', '1:4', '1:8', '2:3', '3:2', '3:4', '4:1', '4:3', '4:5', '5:4', '8:1', '9:16', '16:9', '21:9'], 'ui_type': 'dropdown'}, 'resolution': {'enum': ['1K', '2K', '4K'], 'ui_type': 'dropdown'}, 'output_format': {'enum': ['jpg', 'png'], 'ui_type': 'dropdown'}},
    file_input_params={"image_input": _IMAGE_TYPES, },
    param_help={'image_input': 'Optional. Up to 14 images for editing, style transfer, or fusion.', 'google_search': 'Ground generation in live web facts (weather, news, scores).', 'resolution': 'Higher resolutions take longer.'},
    high_impact_params=['resolution', 'image_input'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/google/nano-banana-2",
    pricing_notes="Per output image on Replicate; see billing page for resolution tiers.",
    output_notes="Single image URI.",
)

FLUX_2_MAX = ModelConfig(
    name="flux-2-max",
    display_name="Flux 2 Max",
    model_type="image",
    replicate_id="black-forest-labs/flux-2-max",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="black-forest-labs/flux-2-max",
    provider_endpoint="versionless",
    provider_category="Maximum fidelity",
    provider_summary="Black Forest Labs' highest-fidelity Flux 2 tier. Use when visual detail and polish matter more than speed or cost. Supports reference-image editing.",
    strength_tags=['max_fidelity', 'reference_editing', 'photorealism'],
    workflow_tags=['text_to_image', 'image_edit', 'max_quality'],
    media_roles={'prompt': 'Prompt', 'input_images': 'Reference images'},
    balanced_params=['prompt', 'input_images', 'aspect_ratio', 'resolution'],
    advanced_params=['safety_tolerance', 'seed', 'output_format', 'output_quality', 'width', 'height'],
    defaults={'aspect_ratio': '1:1', 'resolution': '1 MP', 'safety_tolerance': 2, 'output_format': 'webp', 'output_quality': 80},
    param_constraints={'aspect_ratio': {'enum': ['match_input_image', 'custom', '1:1', '16:9', '3:2', '2:3', '4:5', '5:4', '9:16', '3:4', '4:3'], 'ui_type': 'dropdown'}, 'resolution': {'enum': ['match_input_image', '0.5 MP', '1 MP', '2 MP', '4 MP'], 'ui_type': 'dropdown'}, 'safety_tolerance': {'min': 1, 'max': 5, 'ui_type': 'slider'}, 'output_quality': {'min': 0, 'max': 100, 'ui_type': 'slider'}, 'width': {'min': 256, 'max': 2048, 'nullable': True}, 'height': {'min': 256, 'max': 2048, 'nullable': True}, 'output_format': {'enum': ['webp', 'jpg', 'png'], 'ui_type': 'dropdown'}, 'seed': {'nullable': True}},
    file_input_params={"input_images": _IMAGE_TYPES, },
    param_help={'input_images': 'Up to 8 reference images for editing or style guidance.', 'resolution': 'Higher megapixel targets increase cost and time.'},
    high_impact_params=['resolution', 'input_images'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/black-forest-labs/flux-2-max",
    pricing_notes="~$0.04/run plus per-megapixel input/output fees on Replicate (2026-06-14).",
    output_notes="Single image URI.",
)

FLUX_2_PRO = ModelConfig(
    name="flux-2-pro",
    display_name="Flux 2 Pro",
    model_type="image",
    replicate_id="black-forest-labs/flux-2-pro",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="black-forest-labs/flux-2-pro",
    provider_endpoint="versionless",
    provider_category="Pro quality + editing",
    provider_summary="High-quality Flux 2 generation and editing with up to eight reference images. A balanced pro tier below Max for production-quality stills and guided edits.",
    strength_tags=['high_quality', 'reference_editing', 'balanced'],
    workflow_tags=['text_to_image', 'image_edit'],
    media_roles={'prompt': 'Prompt', 'input_images': 'Reference images'},
    balanced_params=['prompt', 'input_images', 'aspect_ratio', 'resolution'],
    advanced_params=['safety_tolerance', 'seed', 'output_format', 'output_quality', 'width', 'height'],
    defaults={'aspect_ratio': '1:1', 'resolution': '1 MP', 'safety_tolerance': 2, 'output_format': 'webp', 'output_quality': 80},
    param_constraints={'aspect_ratio': {'enum': ['match_input_image', 'custom', '1:1', '16:9', '3:2', '2:3', '4:5', '5:4', '9:16', '3:4', '4:3'], 'ui_type': 'dropdown'}, 'resolution': {'enum': ['match_input_image', '0.5 MP', '1 MP', '2 MP', '4 MP'], 'ui_type': 'dropdown'}, 'safety_tolerance': {'min': 1, 'max': 5, 'ui_type': 'slider'}, 'output_quality': {'min': 0, 'max': 100, 'ui_type': 'slider'}, 'width': {'min': 256, 'max': 2048, 'nullable': True}, 'height': {'min': 256, 'max': 2048, 'nullable': True}, 'output_format': {'enum': ['webp', 'jpg', 'png'], 'ui_type': 'dropdown'}, 'seed': {'nullable': True}},
    file_input_params={"input_images": _IMAGE_TYPES, },
    param_help={'input_images': 'Up to 8 images for editing or visual guidance.'},
    high_impact_params=['resolution', 'input_images'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/black-forest-labs/flux-2-pro",
    pricing_notes="Per-run and per-megapixel pricing on Replicate; typically below Max.",
    output_notes="Single image URI.",
)

SEEDREAM_4_5 = ModelConfig(
    name="seedream-4.5",
    display_name="Seedream 4.5",
    model_type="image",
    replicate_id="bytedance/seedream-4.5",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="bytedance/seedream-4.5",
    provider_endpoint="versionless",
    provider_category="Cinematic + spatial reasoning",
    provider_summary="ByteDance Seedream 4.5 for cinematic, film-like stills with strong spatial layout and world-knowledge grounding. Supports reference editing and multi-image batches (up to 15).",
    strength_tags=['cinematic', 'spatial_reasoning', 'multi_output', 'knowledge_grounded'],
    workflow_tags=['text_to_image', 'image_edit', 'multi_output'],
    media_roles={'prompt': 'Prompt', 'image_input': 'Reference images'},
    balanced_params=['prompt', 'image_input', 'size', 'aspect_ratio', 'max_images'],
    advanced_params=['sequential_image_generation', 'width', 'height', 'disable_safety_checker'],
    defaults={'size': '2K', 'aspect_ratio': 'match_input_image', 'sequential_image_generation': 'disabled', 'max_images': 1, 'disable_safety_checker': False},
    param_constraints={'size': {'enum': ['2K', '4K', 'custom'], 'ui_type': 'dropdown'}, 'aspect_ratio': {'enum': ['match_input_image', '1:1', '4:3', '3:4', '4:5', '5:4', '16:9', '9:16', '3:2', '2:3', '21:9', '9:21'], 'ui_type': 'dropdown'}, 'max_images': {'min': 1, 'max': 15, 'ui_type': 'slider'}, 'sequential_image_generation': {'enum': ['disabled', 'auto'], 'ui_type': 'dropdown'}, 'width': {'min': 1024, 'max': 4096}, 'height': {'min': 1024, 'max': 4096}},
    file_input_params={"image_input": _IMAGE_TYPES, },
    param_help={'max_images': 'How many images to generate in one run.', 'sequential_image_generation': 'Auto can produce related image series.'},
    high_impact_params=['size', 'max_images'],
    multi_output=True,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/bytedance/seedream-4.5",
    pricing_notes="Per output image on Replicate; 2K/4K sizes affect cost.",
    output_notes="Multiple image URIs.",
)

IMAGEN_4_ULTRA = ModelConfig(
    name="imagen-4-ultra",
    display_name="Imagen 4 Ultra",
    model_type="image",
    replicate_id="google/imagen-4-ultra",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="google/imagen-4-ultra",
    provider_endpoint="versionless",
    provider_category="Ultra quality (text-to-image)",
    provider_summary="Google Imagen 4 Ultra — choose when quality matters more than speed and cost. Pure text-to-image with strong safety filters.",
    strength_tags=['max_quality', 'text_to_image', 'photorealism'],
    workflow_tags=['text_to_image', 'max_quality'],
    media_roles={'prompt': 'Prompt'},
    balanced_params=['prompt', 'aspect_ratio', 'image_size'],
    advanced_params=['safety_filter_level', 'output_format'],
    defaults={'aspect_ratio': '1:1', 'image_size': '1K', 'safety_filter_level': 'block_only_high', 'output_format': 'jpg'},
    param_constraints={'aspect_ratio': {'enum': ['1:1', '9:16', '16:9', '3:4', '4:3'], 'ui_type': 'dropdown'}, 'image_size': {'enum': ['1K', '2K'], 'ui_type': 'dropdown'}, 'safety_filter_level': {'enum': ['block_low_and_above', 'block_medium_and_above', 'block_only_high'], 'ui_type': 'dropdown'}, 'output_format': {'enum': ['jpg', 'png'], 'ui_type': 'dropdown'}},
    file_input_params={},
    param_help={'image_size': '2K is slower and costlier than 1K.'},
    high_impact_params=['image_size'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/google/imagen-4-ultra",
    pricing_notes="Per output image on Replicate; Ultra tier priced above Fast.",
    output_notes="Single image URI.",
)

SEEDREAM_5_LITE = ModelConfig(
    name="seedream-5-lite",
    display_name="Seedream 5 Lite",
    model_type="image",
    replicate_id="bytedance/seedream-5-lite",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="bytedance/seedream-5-lite",
    provider_endpoint="versionless",
    provider_category="Reasoning + example editing",
    provider_summary="Seedream 5.0 lite with built-in reasoning, example-based editing, and deep domain knowledge. Good for complex instructions and reference-driven edits; can emit multiple images.",
    strength_tags=['reasoning', 'example_editing', 'multi_output', 'domain_knowledge'],
    workflow_tags=['text_to_image', 'image_edit', 'multi_output'],
    media_roles={'prompt': 'Prompt', 'image_input': 'Example / reference images'},
    balanced_params=['prompt', 'image_input', 'size', 'aspect_ratio', 'max_images'],
    advanced_params=['sequential_image_generation', 'output_format'],
    defaults={'size': '2K', 'aspect_ratio': 'match_input_image', 'sequential_image_generation': 'disabled', 'max_images': 1, 'output_format': 'png'},
    param_constraints={'size': {'enum': ['2K', '3K'], 'ui_type': 'dropdown'}, 'aspect_ratio': {'enum': ['match_input_image', '1:1', '4:3', '3:4', '16:9', '9:16', '3:2', '2:3', '21:9'], 'ui_type': 'dropdown'}, 'max_images': {'min': 1, 'max': 15, 'ui_type': 'slider'}, 'sequential_image_generation': {'enum': ['disabled', 'auto'], 'ui_type': 'dropdown'}, 'output_format': {'enum': ['png', 'jpeg'], 'ui_type': 'dropdown'}},
    file_input_params={"image_input": _IMAGE_TYPES, },
    param_help={'image_input': 'Reference images for example-based editing.', 'max_images': 'Batch count per run.'},
    high_impact_params=['size', 'max_images'],
    multi_output=True,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/bytedance/seedream-5-lite",
    pricing_notes="Per output image on Replicate.",
    output_notes="Multiple image URIs.",
)

FLUX_2_FLEX = ModelConfig(
    name="flux-2-flex",
    display_name="Flux 2 Flex",
    model_type="image",
    replicate_id="black-forest-labs/flux-2-flex",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="black-forest-labs/flux-2-flex",
    provider_endpoint="versionless",
    provider_category="Flexible max-quality editing",
    provider_summary="Most flexible Flux 2 tier: up to ten reference images plus tunable steps and guidance for max-quality generation or editing.",
    strength_tags=['max_quality', 'reference_editing', 'tunable', 'flexible'],
    workflow_tags=['text_to_image', 'image_edit', 'max_quality'],
    media_roles={'prompt': 'Prompt', 'input_images': 'Reference images'},
    balanced_params=['prompt', 'input_images', 'aspect_ratio', 'resolution'],
    advanced_params=['prompt_upsampling', 'steps', 'guidance', 'safety_tolerance', 'seed', 'output_format', 'output_quality', 'width', 'height'],
    defaults={'aspect_ratio': '1:1', 'resolution': '1 MP', 'safety_tolerance': 2, 'prompt_upsampling': True, 'steps': 30, 'guidance': 4.5, 'output_format': 'webp', 'output_quality': 80},
    param_constraints={'aspect_ratio': {'enum': ['match_input_image', 'custom', '1:1', '16:9', '3:2', '2:3', '4:5', '5:4', '9:16', '3:4', '4:3'], 'ui_type': 'dropdown'}, 'resolution': {'enum': ['match_input_image', '0.5 MP', '1 MP', '2 MP', '4 MP'], 'ui_type': 'dropdown'}, 'steps': {'min': 1, 'max': 50, 'ui_type': 'slider'}, 'guidance': {'min': 1.5, 'max': 10, 'ui_type': 'slider'}, 'safety_tolerance': {'min': 1, 'max': 5, 'ui_type': 'slider'}, 'output_quality': {'min': 0, 'max': 100, 'ui_type': 'slider'}, 'output_format': {'enum': ['webp', 'jpg', 'png'], 'ui_type': 'dropdown'}, 'seed': {'nullable': True}},
    file_input_params={"input_images": _IMAGE_TYPES, },
    param_help={'steps': 'More steps can improve detail but take longer.', 'input_images': 'Up to 10 reference images.'},
    high_impact_params=['steps', 'guidance', 'input_images'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/black-forest-labs/flux-2-flex",
    pricing_notes="Per-run and per-megapixel on Replicate; Flex is the premium Flux 2 tier.",
    output_notes="Single image URI.",
)

IDEOGRAM_V3_TURBO = ModelConfig(
    name="ideogram-v3-turbo",
    display_name="Ideogram V3 Turbo",
    model_type="image",
    replicate_id="ideogram-ai/ideogram-v3-turbo",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="ideogram-ai/ideogram-v3-turbo",
    provider_endpoint="versionless",
    provider_category="Fast design + typography",
    provider_summary="Fastest, cheapest Ideogram v3 — strong realism, creative design, style presets, inpainting (image+mask), and reliable text-in-image.",
    strength_tags=['fast', 'typography', 'inpainting', 'style_presets', 'design'],
    workflow_tags=['text_to_image', 'image_edit', 'typography', 'fast_draft', 'inpainting'],
    media_roles={'prompt': 'Prompt', 'image': 'Source image', 'mask': 'Inpaint mask', 'style_reference_images': 'Style references'},
    balanced_params=['prompt', 'aspect_ratio', 'style_type'],
    advanced_params=['magic_prompt_option', 'image', 'mask', 'style_preset', 'style_reference_images', 'seed'],
    defaults={'aspect_ratio': '1:1', 'magic_prompt_option': 'Auto', 'style_type': 'None', 'style_preset': 'None'},
    param_constraints={'aspect_ratio': {'enum': ['1:3', '3:1', '1:2', '2:1', '9:16', '16:9', '10:16', '16:10', '2:3', '3:2', '3:4', '4:3', '4:5', '5:4', '1:1'], 'ui_type': 'dropdown'}, 'magic_prompt_option': {'enum': ['Auto', 'On', 'Off'], 'ui_type': 'dropdown'}, 'style_type': {'enum': ['None', 'Auto', 'General', 'Realistic', 'Design'], 'ui_type': 'dropdown'}, 'seed': {'nullable': True}},
    file_input_params={"image": _IMAGE_TYPES, "mask": _IMAGE_TYPES, "style_reference_images": _IMAGE_TYPES, },
    param_help={'image': 'Optional source for edit/inpaint workflows.', 'mask': 'White areas are repainted; requires image.', 'magic_prompt_option': 'Auto expands short prompts for better results.'},
    high_impact_params=['style_type', 'image'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/ideogram-ai/ideogram-v3-turbo",
    pricing_notes="Per output image; among the lowest p50 costs on Replicate (~$0.0006).",
    output_notes="Single image URI.",
)

RECRAFT_V4 = ModelConfig(
    name="recraft-v4",
    display_name="Recraft V4",
    model_type="image",
    replicate_id="recraft-ai/recraft-v4",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="recraft-ai/recraft-v4",
    provider_endpoint="versionless",
    provider_category="Design-first raster",
    provider_summary="Recraft's design-taste raster model: strong prompt accuracy, art-directed composition, and integrated text rendering. Fast and cost-efficient at standard resolution.",
    strength_tags=['design', 'typography', 'prompt_accuracy', 'cost_efficient'],
    workflow_tags=['text_to_image', 'typography', 'design'],
    media_roles={'prompt': 'Prompt'},
    balanced_params=['prompt', 'aspect_ratio', 'size'],
    advanced_params=[],
    defaults={'aspect_ratio': '1:1', 'size': '1024x1024'},
    param_constraints={'aspect_ratio': {'enum': ['Not set', '1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '1:2', '2:1', '14:10', '10:14', '4:5', '5:4', '6:10'], 'ui_type': 'dropdown'}, 'size': {'enum': ['1024x1024', '1536x768', '768x1536', '1280x832', '832x1280', '1216x896', '896x1216', '1152x896', '896x1152', '832x1344', '1280x896', '896x1280', '1344x768', '768x1344'], 'ui_type': 'dropdown'}},
    file_input_params={},
    param_help={},
    high_impact_params=['size'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/recraft-ai/recraft-v4",
    pricing_notes="Per output image on Replicate (~$0.0013 p50, 2026-06-14).",
    output_notes="Single image URI.",
)

RECRAFT_V4_SVG = ModelConfig(
    name="recraft-v4-svg",
    display_name="Recraft V4 SVG",
    model_type="image",
    replicate_id="recraft-ai/recraft-v4-svg",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="recraft-ai/recraft-v4-svg",
    provider_endpoint="versionless",
    provider_category="Vector / SVG output",
    provider_summary="Production-ready SVG vectors from text — Recraft design taste with clean geometry, structured layers, and editable paths for logos, icons, and brand assets.",
    strength_tags=['vector', 'svg', 'design', 'logos'],
    workflow_tags=['text_to_image', 'vector_svg', 'design'],
    media_roles={'prompt': 'Prompt'},
    balanced_params=['prompt', 'aspect_ratio', 'size'],
    advanced_params=[],
    defaults={'aspect_ratio': '1:1', 'size': '1024x1024'},
    param_constraints={'aspect_ratio': {'enum': ['Not set', '1:1', '4:3', '3:4', '3:2', '2:3', '16:9', '9:16', '1:2', '2:1', '14:10', '10:14', '4:5', '5:4', '6:10'], 'ui_type': 'dropdown'}, 'size': {'enum': ['1024x1024', '1536x768', '768x1536', '1280x832', '832x1280', '1216x896', '896x1216', '1152x896', '896x1152', '832x1344', '1280x896', '896x1280', '1344x768', '768x1344'], 'ui_type': 'dropdown'}},
    file_input_params={},
    param_help={},
    high_impact_params=['size'],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/recraft-ai/recraft-v4-svg",
    pricing_notes="Per output image on Replicate.",
    output_notes="Single image URI.",
)

IMAGEN_4_FAST = ModelConfig(
    name="imagen-4-fast",
    display_name="Imagen 4 Fast",
    model_type="image",
    replicate_id="google/imagen-4-fast",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="google/imagen-4-fast",
    provider_endpoint="versionless",
    provider_category="Fast draft (text-to-image)",
    provider_summary="Google Imagen 4 Fast when speed and cost beat maximum fidelity. Good for quick drafts and exploration.",
    strength_tags=['fast', 'text_to_image', 'cost_efficient'],
    workflow_tags=['text_to_image', 'fast_draft'],
    media_roles={'prompt': 'Prompt'},
    balanced_params=['prompt', 'aspect_ratio'],
    advanced_params=['safety_filter_level', 'output_format'],
    defaults={'aspect_ratio': '1:1', 'safety_filter_level': 'block_only_high', 'output_format': 'jpg'},
    param_constraints={'aspect_ratio': {'enum': ['1:1', '9:16', '16:9', '3:4', '4:3'], 'ui_type': 'dropdown'}, 'safety_filter_level': {'enum': ['block_low_and_above', 'block_medium_and_above', 'block_only_high'], 'ui_type': 'dropdown'}, 'output_format': {'enum': ['jpg', 'png'], 'ui_type': 'dropdown'}},
    file_input_params={},
    param_help={},
    high_impact_params=[],
    multi_output=False,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/google/imagen-4-fast",
    pricing_notes="Per output image; lower cost than Ultra on Replicate.",
    output_notes="Single image URI.",
)

FLUX_SCHNELL = ModelConfig(
    name="flux-schnell",
    display_name="Flux Schnell",
    model_type="image",
    replicate_id="black-forest-labs/flux-schnell",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="black-forest-labs/flux-schnell",
    provider_endpoint="versionless",
    provider_category="Ultra-fast draft",
    provider_summary="The fastest Flux model for rapid iteration and personal workflows. Can emit up to four images per run.",
    strength_tags=['ultra_fast', 'draft', 'multi_output', 'iterations'],
    workflow_tags=['text_to_image', 'fast_draft', 'multi_output'],
    media_roles={'prompt': 'Prompt'},
    balanced_params=['prompt', 'aspect_ratio', 'num_outputs'],
    advanced_params=['num_inference_steps', 'seed', 'output_format', 'output_quality', 'megapixels', 'go_fast', 'disable_safety_checker'],
    defaults={'aspect_ratio': '1:1', 'num_outputs': 1, 'num_inference_steps': 4, 'output_format': 'webp', 'output_quality': 80, 'go_fast': True, 'megapixels': '1', 'disable_safety_checker': False},
    param_constraints={'aspect_ratio': {'enum': ['1:1', '16:9', '21:9', '3:2', '2:3', '4:5', '5:4', '3:4', '4:3', '9:16', '9:21'], 'ui_type': 'dropdown'}, 'num_outputs': {'min': 1, 'max': 4, 'ui_type': 'slider'}, 'num_inference_steps': {'min': 1, 'max': 4, 'ui_type': 'slider'}, 'megapixels': {'enum': ['1', '0.25'], 'ui_type': 'dropdown'}, 'output_quality': {'min': 0, 'max': 100, 'ui_type': 'slider'}, 'output_format': {'enum': ['webp', 'jpg', 'png'], 'ui_type': 'dropdown'}, 'seed': {'nullable': True}},
    file_input_params={},
    param_help={'num_outputs': 'Generate 1–4 variations per run.'},
    high_impact_params=['num_outputs'],
    multi_output=True,
    metadata_verified_date="2026-06-14",
    replicate_page_url="https://replicate.com/black-forest-labs/flux-schnell",
    pricing_notes="~$0.0015 p50 per run on Replicate (2026-06-14).",
    output_notes="Multiple image URIs.",
)

IMAGE_MODELS: list[ModelConfig] = [
    NANO_BANANA_2,
    FLUX_2_MAX,
    FLUX_2_PRO,
    SEEDREAM_4_5,
    IMAGEN_4_ULTRA,
    SEEDREAM_5_LITE,
    FLUX_2_FLEX,
    IDEOGRAM_V3_TURBO,
    RECRAFT_V4,
    RECRAFT_V4_SVG,
    IMAGEN_4_FAST,
    FLUX_SCHNELL
]
