"""Replicate 3D and texture model catalogue."""

# ruff: noqa: E501

from __future__ import annotations

from src.domain import ModelConfig

# ═══════════════════════════════════════════════
#  3D MODELS
# ═══════════════════════════════════════════════

HUNYUAN3D_2 = ModelConfig(
    name="hunyuan3d-2",
    display_name="Hunyuan3D 2.0",
    model_type="3d",
    replicate_id="tencent/hunyuan3d-2",
    supports_text=False,  # NOTE: Replicate schema shows image-only
    supports_image=True,
    requires_image=True,
    provider="replicate",
    provider_model_id="tencent/hunyuan3d-2",
    provider_endpoint="versioned",
    provider_category="Image-to-3D (single view)",
    provider_summary="Tencent Hunyuan3D 2 — turn one clear subject photo into a textured 3D mesh. Tunable steps, guidance, and octree resolution.",
    strength_tags=["image_to_3d", "single_view", "textured_mesh"],
    media_roles={
        "image": "Subject image",
    },
    workflow_tags=["image_to_3d"],
    balanced_params=[
        "image",
        "seed",
    ],
    advanced_params=[
        "steps",
        "guidance_scale",
        "octree_resolution",
        "remove_background",
    ],
    defaults={
        "seed": 1234,
        "steps": 50,
        "guidance_scale": 5.5,
        "octree_resolution": 256,
        "remove_background": True,
    },
    param_constraints={
        "steps": {"min": 20, "max": 50, "ui_type": "number"},
        "guidance_scale": {"min": 1.0, "max": 20.0, "ui_type": "number"},
        "octree_resolution": {"enum": [256, 384, 512], "ui_type": "dropdown"},
    },
    param_help={
        "steps": "Inference steps. Higher improves quality (plateau ~40).",
        "guidance_scale": "Prompt vs creativity. 5-8 typical for 3D.",
        "octree_resolution": "Voxel res (256 fast; 512 sharper/heavier).",
        "remove_background": "Auto-remove bg from input for clean subject.",
    },
    high_impact_params=["steps", "guidance_scale", "octree_resolution"],
    presets={
        "Fast": {
            "steps": 20,
            "guidance_scale": 3.0,
            "octree_resolution": 256,
            "remove_background": True,
        },
        "Balanced": {
            "steps": 50,
            "guidance_scale": 5.5,
            "octree_resolution": 256,
            "remove_background": True,
        },
        "High quality": {
            "steps": 50,
            "guidance_scale": 8.0,
            "octree_resolution": 512,
            "remove_background": True,
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/tencent/hunyuan3d-2",
    pricing_notes="L40S compute-time estimate from pricing table.",
    output_notes="Object output with mesh field.",
)

TRELLIS_2 = ModelConfig(
    name="trellis-2",
    display_name="TRELLIS 2",
    model_type="3d",
    replicate_id="fishwowater/trellis2",
    supports_text=False,
    supports_image=True,
    requires_image=True,
    provider="replicate",
    provider_model_id="fishwowater/trellis2",
    provider_endpoint="versioned",
    provider_category="High-detail image-to-3D",
    provider_summary="TRELLIS 2 cascade pipeline for detailed meshes with optional preview video. Extensive quality knobs for shape, texture, and decimation.",
    strength_tags=["image_to_3d", "high_detail", "preview_video", "tunable"],
    media_roles={
        "image": "Subject image",
    },
    workflow_tags=["image_to_3d"],
    balanced_params=[
        "image",
        "seed",
        "pipeline_type",
    ],
    advanced_params=[
        "generate_model",
        "generate_video",
        "texture_size",
        "decimation_target",
        "preprocess_image",
        "sparse_structure_steps",
        "shape_slat_steps",
        "tex_slat_steps",
        "shape_slat_guidance_strength",
        "tex_slat_guidance_strength",
    ],
    advanced_param_groups=[
        ("Toggles", ["generate_model", "generate_video", "preprocess_image"]),
        (
            "Quality & steps",
            [
                "pipeline_type",
                "sparse_structure_steps",
                "shape_slat_steps",
                "tex_slat_steps",
                "shape_slat_guidance_strength",
                "tex_slat_guidance_strength",
            ],
        ),
        ("Mesh & texture", ["texture_size", "decimation_target"]),
    ],
    defaults={
        "seed": 42,
        "pipeline_type": "1024_cascade",
        "generate_model": True,
        "generate_video": True,
        "texture_size": 4096,
        "decimation_target": 1_000_000,
        "preprocess_image": True,
        "sparse_structure_steps": 12,
        "shape_slat_steps": 12,
        "tex_slat_steps": 12,
        "shape_slat_guidance_strength": 7.5,
        "tex_slat_guidance_strength": 1.0,
    },
    param_constraints={
        "pipeline_type": {
            "enum": ["512", "1024", "1024_cascade", "1536_cascade"],
            "ui_type": "dropdown",
        },
        "texture_size": {"min": 1024, "max": 8192, "ui_type": "number"},
        "decimation_target": {"min": 100000, "max": 2000000, "ui_type": "number"},
        "sparse_structure_steps": {"min": 1, "max": 50, "ui_type": "number"},
        "shape_slat_steps": {"min": 1, "max": 50, "ui_type": "number"},
        "tex_slat_steps": {"min": 1, "max": 50, "ui_type": "number"},
        "shape_slat_guidance_strength": {"min": 0.0, "max": 15.0, "ui_type": "number"},
        "tex_slat_guidance_strength": {"min": 0.0, "max": 15.0, "ui_type": "number"},
    },
    param_help={
        "pipeline_type": "Higher cascade = better quality, slower/expensive.",
        "texture_size": "Higher = sharper textures, larger files, longer time.",
        "decimation_target": "Target tris after simplify. Lower = lighter files.",
        "sparse_structure_steps": "Coarse structure steps (higher helps complex).",
        "shape_slat_steps": "Shape detail refinement steps.",
        "tex_slat_steps": "Texture detail steps.",
        "shape_slat_guidance_strength": "Shape fidelity to input (higher=faithful).",
        "tex_slat_guidance_strength": "Texture adherence to prompt/image.",
    },
    high_impact_params=[
        "pipeline_type",
        "texture_size",
        "decimation_target",
        "shape_slat_guidance_strength",
    ],
    presets={
        "Fast preview": {
            "pipeline_type": "512",
            "generate_video": False,
            "texture_size": 1024,
            "decimation_target": 100_000,
            "sparse_structure_steps": 6,
            "shape_slat_steps": 6,
            "tex_slat_steps": 6,
            "shape_slat_guidance_strength": 5.0,
            "tex_slat_guidance_strength": 1.0,
        },
        "Balanced": {
            "pipeline_type": "1024_cascade",
            "generate_model": True,
            "generate_video": True,
            "texture_size": 4096,
            "decimation_target": 1_000_000,
            "sparse_structure_steps": 12,
            "shape_slat_steps": 12,
            "tex_slat_steps": 12,
            "shape_slat_guidance_strength": 7.5,
            "tex_slat_guidance_strength": 1.0,
        },
        "High quality / detail": {
            "pipeline_type": "1536_cascade",
            "texture_size": 8192,
            "decimation_target": 2_000_000,
            "sparse_structure_steps": 25,
            "shape_slat_steps": 25,
            "tex_slat_steps": 25,
            "shape_slat_guidance_strength": 10.0,
            "tex_slat_guidance_strength": 2.0,
        },
        "Low poly / stylized": {
            "pipeline_type": "1024",
            "texture_size": 2048,
            "decimation_target": 100_000,
            "sparse_structure_steps": 8,
            "shape_slat_steps": 8,
            "tex_slat_steps": 8,
            "shape_slat_guidance_strength": 4.0,
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/fishwowater/trellis2",
    pricing_notes="A100-80GB compute-time estimate from pricing table.",
    output_notes="model_file + optional preview video.",
    multi_output=True,
)

HUNYUAN_3D_3_1 = ModelConfig(
    name="hunyuan-3d-3.1",
    display_name="Hunyuan 3D 3.1",
    model_type="3d",
    replicate_id="tencent/hunyuan-3d-3.1",
    supports_text=True,
    supports_image=True,
    requires_text=False,  # Either prompt or image is sufficient
    requires_image=False,  # Either prompt or image is sufficient
    provider="replicate",
    provider_model_id="tencent/hunyuan-3d-3.1",
    provider_endpoint="versionless",
    provider_category="Text or image to 3D",
    provider_summary="Hunyuan 3D 3.1 — create assets from a text description or one subject image (not both). Face count, PBR, and geometry-only modes.",
    strength_tags=["text_to_3d", "image_to_3d", "pbr", "flexible_input"],
    media_roles={
        "prompt": "Describe the 3D model",
        "image": "Subject image",
    },
    workflow_tags=["text_to_3d", "image_to_3d"],
    generation_modes=[
        ("text", "Create from text"),
        ("image", "Create from image"),
    ],
    default_generation_mode="text",
    balanced_params=[
        "prompt",
        "image",
        "generate_type",
        "face_count",
    ],
    advanced_params=[
        "enable_pbr",
    ],
    defaults={
        "generate_type": "Normal",
        "face_count": 500000,
        "enable_pbr": False,
    },
    param_constraints={
        "generate_type": {
            "enum": ["Normal", "Geometry"],
            "ui_type": "dropdown",
        },
        "face_count": {"min": 40000, "max": 1500000, "ui_type": "slider"},
        "prompt": {"nullable": True, "max": 1024},
        "image": {"nullable": True},
    },
    # Exactly one of prompt or image must be provided; both together is invalid.
    mutual_exclusion=[("prompt", "image")],
    required_one_of=[("prompt", "image")],
    param_help={
        "face_count": "Target faces. Higher detail = heavier files, slower use.",
        "generate_type": "Normal=textured; Geometry=pure shape (no tex).",
        "enable_pbr": "Generate PBR maps (extra compute).",
    },
    high_impact_params=["face_count"],
    presets={
        "Low poly / fast": {
            "face_count": 100_000,
            "generate_type": "Normal",
            "enable_pbr": False,
        },
        "Balanced": {
            "face_count": 500_000,
            "generate_type": "Normal",
            "enable_pbr": False,
        },
        "High detail": {
            "face_count": 1_000_000,
            "generate_type": "Normal",
            "enable_pbr": True,
        },
        "Pure geometry": {
            "face_count": 800_000,
            "generate_type": "Geometry",
            "enable_pbr": False,
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/tencent/hunyuan-3d-3.1",
    pricing_notes="Replicate page: per-unit pricing (~$0.16/unit); CPU hardware.",
    output_notes="Single 3D asset URI (versionless API).",
)

HUNYUAN3D_2MV = ModelConfig(
    name="hunyuan3d-2mv",
    display_name="Hunyuan3D 2 Multiview",
    model_type="3d",
    replicate_id="tencent/hunyuan3d-2mv",
    supports_text=False,
    supports_image=False,
    requires_image=False,
    provider="replicate",
    provider_model_id="tencent/hunyuan3d-2mv",
    provider_endpoint="versioned",
    provider_category="Multiview image-to-3D",
    provider_summary="Hunyuan3D 2 Multiview — front view required; optional side/back views improve consistency. Exports glb/obj/ply/stl.",
    strength_tags=["multiview_to_3d", "consistent", "export_formats"],
    media_roles={
        "front_image": "Front view (required)",
        "back_image": "Back view (optional)",
        "left_image": "Left view (optional)",
        "right_image": "Right view (optional)",
    },
    workflow_tags=["multiview_to_3d"],
    file_input_params={
        "front_image": ["png", "jpg", "jpeg", "webp"],
        "back_image": ["png", "jpg", "jpeg", "webp"],
        "left_image": ["png", "jpg", "jpeg", "webp"],
        "right_image": ["png", "jpg", "jpeg", "webp"],
    },
    required_file_params=["front_image"],
    balanced_params=[
        "front_image",
        "file_type",
        "target_face_num",
    ],
    advanced_params=[
        "back_image",
        "left_image",
        "right_image",
        "steps",
        "guidance_scale",
        "octree_resolution",
        "num_chunks",
        "remove_background",
        "seed",
        "randomize_seed",
    ],
    defaults={
        "file_type": "glb",
        "target_face_num": 10000,
        "steps": 30,
        "guidance_scale": 5.0,
        "octree_resolution": 256,
        "num_chunks": 200000,
        "remove_background": True,
        "seed": 1234,
        "randomize_seed": True,
    },
    param_constraints={
        "file_type": {"enum": ["glb", "obj", "ply", "stl"], "ui_type": "dropdown"},
        "target_face_num": {"min": 100, "max": 1000000, "ui_type": "number"},
        "steps": {"min": 1, "max": 100, "ui_type": "number"},
        "octree_resolution": {"min": 16, "max": 512, "ui_type": "number"},
        "num_chunks": {"min": 1000, "max": 5000000, "ui_type": "number"},
    },
    param_help={
        "target_face_num": "Approx faces in final mesh (post decimation).",
        "steps": "Overall inference steps.",
        "guidance_scale": "Image prompt strength.",
        "num_chunks": "Internal chunks; higher helps detailed subjects.",
        "octree_resolution": "Internal res (higher=detail, more mem/time).",
    },
    high_impact_params=[
        "steps",
        "guidance_scale",
        "octree_resolution",
        "target_face_num",
    ],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/tencent/hunyuan3d-2mv",
    pricing_notes="Replicate page ~$0.14/run on L40S; time varies with settings.",
    output_notes="Single 3D mesh URI (glb/obj/ply/stl via file_type).",
)

TEXT2TEX = ModelConfig(
    name="text2tex",
    display_name="Text2Tex",
    model_type="3d",
    replicate_id="adirik/text2tex",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    provider="replicate",
    provider_model_id="adirik/text2tex",
    provider_endpoint="versioned",
    provider_category="Text-driven mesh texturing",
    provider_summary="Upload an .obj mesh and describe the surface appearance. Multi-viewpoint diffusion texturing with refinement passes.",
    strength_tags=["texturing", "obj_mesh", "multi_viewpoint"],
    media_roles={
        "prompt": "Texture description",
        "obj_file": "3D mesh file (.obj)",
    },
    workflow_tags=["texturing"],
    file_input_params={"obj_file": ["obj"]},
    required_file_params=["obj_file"],
    balanced_params=[
        "prompt",
        "obj_file",
    ],
    advanced_params=[
        "negative_prompt",
        "ddim_steps",
        "new_strength",
        "update_strength",
        "num_viewpoints",
        "viewpoint_mode",
        "update_steps",
        "update_mode",
        "seed",
    ],
    defaults={
        "negative_prompt": "",
        "ddim_steps": 50,
        "new_strength": 1.0,
        "update_strength": 0.3,
        "num_viewpoints": 36,
        "viewpoint_mode": "predefined",
        "update_steps": 20,
        "update_mode": "heuristic",
    },
    param_constraints={
        "new_strength": {"min": 0.0, "max": 1.0, "ui_type": "number"},
        "update_strength": {"min": 0.0, "max": 1.0, "ui_type": "number"},
        "num_viewpoints": {
            "enum": [1, 2, 4, 6, 12, 20, 36, 68],
            "ui_type": "dropdown",
        },
        "viewpoint_mode": {
            "enum": ["predefined", "hemisphere"],
            "ui_type": "dropdown",
        },
        "update_mode": {
            "enum": ["sequential", "heuristic", "random"],
            "ui_type": "dropdown",
        },
        "seed": {"nullable": True},
    },
    advanced_param_groups=[
        ("View sampling (quality & time)", ["num_viewpoints", "viewpoint_mode"]),
        ("Update / refinement", ["update_steps", "update_mode", "update_strength"]),
        ("Diffusion steps", ["ddim_steps", "new_strength"]),
        ("Other", ["negative_prompt", "seed"]),
    ],
    param_help={
        "ddim_steps": "Diffusion steps. Higher=better tex, more time.",
        "new_strength": "New texture vs original (1.0=full replace).",
        "update_strength": "Strength of texture update pass.",
        "num_viewpoints": "Rendered views for tex. More=coverage, slower.",
        "viewpoint_mode": "Viewpoint placement around object.",
        "update_steps": "Texture update/refinement steps.",
    },
    high_impact_params=["num_viewpoints", "ddim_steps", "new_strength"],
    presets={
        "Fast / low views": {
            "num_viewpoints": 6,
            "ddim_steps": 20,
            "new_strength": 0.8,
            "update_steps": 10,
            "update_strength": 0.2,
        },
        "Balanced": {
            "num_viewpoints": 36,
            "ddim_steps": 50,
            "new_strength": 1.0,
            "update_strength": 0.3,
            "update_steps": 20,
            "update_mode": "heuristic",
        },
        "High quality / dense": {
            "num_viewpoints": 68,
            "ddim_steps": 80,
            "new_strength": 1.0,
            "update_strength": 0.5,
            "update_steps": 40,
            "viewpoint_mode": "hemisphere",
        },
        "Stylized / loose": {
            "num_viewpoints": 12,
            "ddim_steps": 30,
            "new_strength": 1.0,
            "update_strength": 0.1,
            "viewpoint_mode": "predefined",
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/adirik/text2tex",
    pricing_notes="L40S compute-time estimate; non-commercial license on model card.",
    output_notes="Textured mesh URI (.obj output).",
)

ADIRIK_TEXTURE = ModelConfig(
    name="adirik-texture",
    display_name="Adirik Texture",
    model_type="3d",
    replicate_id="adirik/texture",
    supports_text=True,
    supports_image=False,
    requires_text=False,
    provider="replicate",
    provider_model_id="adirik/texture",
    provider_endpoint="versioned",
    provider_category="Quick mesh texturing",
    provider_summary="Texture an untextured mesh (obj/glb/ply) from a short prompt. Simpler adirik pipeline than Text2Tex for fast surface looks.",
    strength_tags=["texturing", "untextured_mesh", "fast"],
    media_roles={
        "prompt": "Surface appearance",
        "shape_path": "Untextured mesh file",
    },
    workflow_tags=["texturing"],
    file_input_params={"shape_path": ["obj", "glb", "ply"]},
    required_file_params=["shape_path"],
    balanced_params=[
        "prompt",
        "shape_path",
        "texture_resolution",
    ],
    advanced_params=[
        "guidance_scale",
        "shape_scale",
        "seed",
        "texture_interpolation_mode",
    ],
    defaults={
        "prompt": "A next gen nascar",
        "texture_resolution": 1024,
        "guidance_scale": 10.0,
        "shape_scale": 0.6,
        "seed": 0,
        "texture_interpolation_mode": "bilinear",
    },
    param_constraints={
        "texture_resolution": {"enum": [512, 1024], "ui_type": "dropdown"},
        "guidance_scale": {"min": 0.0, "max": 20.0, "ui_type": "number"},
        "shape_scale": {"min": 0.0, "max": 1.0, "ui_type": "number"},
    },
    param_help={
        "guidance_scale": "Texture vs prompt adherence (higher = stronger).",
        "shape_scale": "Scale applied to input mesh during texturing.",
        "texture_interpolation_mode": "Texture sampling (bilinear usually fine).",
    },
    high_impact_params=["guidance_scale"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/adirik/texture",
    pricing_notes="L40S compute-time estimate from pricing table.",
    output_notes="Array of textured mesh URIs (may return multiple files).",
    multi_output=True,
)

RODIN = ModelConfig(
    name="rodin",
    display_name="Rodin Gen-2",
    model_type="3d",
    replicate_id="hyper3d/rodin",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    requires_image=False,
    provider="replicate",
    provider_model_id="hyper3d/rodin",
    provider_endpoint="versioned",
    provider_category="Text-to-3D (Hyper3D)",
    provider_summary="Hyper3D Rodin Gen-2 — generate textured 3D from text with optional reference image for likeness. Quality tiers and PBR materials.",
    strength_tags=["text_to_3d", "reference_image", "pbr", "quality_tiers"],
    media_roles={
        "prompt": "Describe the 3D model",
        "images": "Reference image (optional)",
    },
    workflow_tags=["text_to_3d"],
    generation_modes=[
        ("text", "Text only"),
        ("reference", "Text + reference image"),
    ],
    default_generation_mode="text",
    file_input_params={"images": ["png", "jpg", "jpeg", "webp"]},
    required_file_params=[],
    balanced_params=[
        "prompt",
        "quality",
        "geometry_file_format",
        "material",
        "mesh_mode",
    ],
    advanced_params=[
        "images",
        "preview_render",
        "seed",
        "use_original_alpha",
        "tapose",
    ],
    defaults={
        "quality": "medium",
        "geometry_file_format": "glb",
        "material": "PBR",
        "mesh_mode": "Quad",
        "preview_render": False,
        "use_original_alpha": False,
        "tapose": False,
        "tier": "Gen-2",
    },
    param_constraints={
        "quality": {
            "enum": ["high", "medium", "low", "extra-low"],
            "ui_type": "dropdown",
        },
        "geometry_file_format": {
            "enum": ["glb", "usdz", "fbx", "obj", "stl"],
            "ui_type": "dropdown",
        },
        "material": {"enum": ["PBR", "Shaded", "All"], "ui_type": "dropdown"},
        "mesh_mode": {"enum": ["Quad", "Raw"], "ui_type": "dropdown"},
        "seed": {"nullable": True},
    },
    param_help={
        "quality": "Higher=better geo/materials (high=slow/expensive).",
        "material": "PBR realistic; Shaded simple; All for both.",
        "mesh_mode": "Quad=clean topo; Raw=max fidelity (may need cleanup).",
        "preview_render": "Small preview render (extra time).",
        "tapose": "Experimental; usually leave off.",
    },
    high_impact_params=["quality", "material"],
    presets={
        "Fast / low quality": {
            "quality": "low",
            "preview_render": False,
            "mesh_mode": "Raw",
        },
        "Balanced (medium)": {
            "quality": "medium",
            "geometry_file_format": "glb",
            "material": "PBR",
            "mesh_mode": "Quad",
            "preview_render": False,
        },
        "High quality": {
            "quality": "high",
            "geometry_file_format": "glb",
            "material": "PBR",
            "mesh_mode": "Quad",
            "preview_render": True,
        },
        "Extra detail (slow)": {
            "quality": "high",
            "preview_render": True,
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/hyper3d/rodin",
    pricing_notes="Cost unknown until verified on Replicate billing page.",
    output_notes="Single 3D asset URI.",
)


THREED_MODELS: list[ModelConfig] = [
    HUNYUAN3D_2,
    HUNYUAN3D_2MV,
    TRELLIS_2,
    HUNYUAN_3D_3_1,
    TEXT2TEX,
    ADIRIK_TEXTURE,
    RODIN,
]
