"""Replicate video model catalogue."""

# ruff: noqa: E501

from __future__ import annotations

from src.domain import ModelConfig

# ═══════════════════════════════════════════════
#  VIDEO MODELS
# ═══════════════════════════════════════════════

_VIDEO_FILE_TYPES = ["mp4", "mov", "webm"]
_IMAGE_FILE_TYPES = ["png", "jpg", "jpeg", "webp"]

WAN_2_7_T2V = ModelConfig(
    name="wan-2.7-t2v",
    display_name="Wan 2.7 T2V",
    model_type="video",
    replicate_id="wan-video/wan-2.7-t2v",
    supports_text=True,
    supports_image=False,
    supports_audio=True,  # accepts audio uri for synchronization
    requires_text=True,
    provider="replicate",
    provider_model_id="wan-video/wan-2.7-t2v",
    provider_endpoint="versionless",
    provider_category="Text-to-video (Wan)",
    provider_summary="Alibaba Wan 2.7 for cinematic text-to-video with prompt expansion, flexible duration (2–15s), and 720p/1080p output. A solid default when you have a script but no start image.",
    strength_tags=["text_to_video", "prompt_expansion", "cinematic", "flexible_duration"],
    workflow_archetype="text_or_image_video",
    workflow_tags=["text_to_video"],
    media_roles={
        "prompt": "Prompt",
    },
    balanced_params=[
        "prompt",
        "duration",
        "aspect_ratio",
        "seed",
        "resolution",
    ],
    advanced_params=[
        "negative_prompt",
        "enable_prompt_expansion",
    ],
    defaults={
        "duration": 5,
        "resolution": "1080p",
        "aspect_ratio": "16:9",
        "seed": -1,
        "enable_prompt_expansion": True,
        "negative_prompt": "",
    },
    param_constraints={
        "duration": {"min": 2, "max": 15, "ui_type": "slider"},
        "resolution": {"enum": ["720p", "1080p"], "ui_type": "dropdown"},
        "aspect_ratio": {
            "enum": ["16:9", "9:16", "1:1", "4:3", "3:4"],
            "ui_type": "dropdown",
        },
        "seed": {"nullable": True},
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/wan-video/wan-2.7-t2v",
    pricing_notes=(
        "~$0.10/s output video (Replicate page); table uses per-second estimate."
    ),
    output_notes="Single video URI.",
)

WAN_2_5_I2V = ModelConfig(
    name="wan-2.5-i2v-fast",
    display_name="Wan 2.5 I2V Fast",
    model_type="video",
    replicate_id="wan-video/wan-2.5-i2v-fast",
    supports_text=True,
    supports_image=True,
    supports_audio=True,
    requires_text=True,
    requires_image=True,
    provider="replicate",
    provider_model_id="wan-video/wan-2.5-i2v-fast",
    provider_endpoint="versionless",
    provider_category="Fast image-to-video",
    provider_summary="Animate a start-frame image into a short clip (5 or 10s). Faster Wan variant tuned for image-to-video when you already have a key visual.",
    strength_tags=["image_to_video", "fast", "start_frame"],
    workflow_archetype="text_or_image_video",
    workflow_tags=["image_to_video"],
    media_roles={
        "prompt": "Prompt",
        "image": "Start frame image",
    },
    balanced_params=[
        "prompt",
        "image",
        "duration",
        "seed",
        "resolution",
    ],
    advanced_params=[
        "negative_prompt",
        "enable_prompt_expansion",
    ],
    defaults={
        "duration": 5,
        "resolution": "720p",
        "seed": -1,
        "enable_prompt_expansion": True,
        "negative_prompt": "",
    },
    param_constraints={
        "duration": {"enum": [5, 10], "ui_type": "dropdown"},
        "resolution": {"enum": ["720p", "1080p"], "ui_type": "dropdown"},
        "seed": {"nullable": True},
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/wan-video/wan-2.5-i2v-fast",
    pricing_notes=(
        "Approx per-second output pricing; verify on Replicate before trusting."
    ),
    output_notes="Single video URI.",
)

SEEDANCE_2_0 = ModelConfig(
    name="seedance-2.0",
    display_name="Seedance 2.0",
    model_type="video",
    replicate_id="bytedance/seedance-2.0",
    supports_text=True,
    supports_image=True,
    supports_audio=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="bytedance/seedance-2.0",
    provider_endpoint="versionless",
    provider_category="Multimodal video + audio",
    provider_summary="ByteDance Seedance 2.0 — full multimodal generation: text, start/end frames, reference images/videos/audio, and optional synced audio. Best when you need rich creative control.",
    strength_tags=["multimodal", "text_to_video", "image_to_video", "reference_media", "audio_sync"],
    workflow_archetype="multimodal_video",
    workflow_tags=["text_to_video", "image_to_video", "multimodal"],
    media_roles={
        "prompt": "Prompt",
        "image": "Start frame image",
        "last_frame_image": "End frame image",
        "reference_images": "Reference image",
        "reference_videos": "Reference video",
        "reference_audios": "Reference audio",
    },
    mutual_exclusion=[
        ("image", "reference_images"),
        ("last_frame_image", "reference_images"),
    ],
    balanced_params=[
        "prompt",
        "duration",
        "aspect_ratio",
        "seed",
        "resolution",
    ],
    advanced_params=[
        "generate_audio",
    ],
    defaults={
        "duration": 5,
        "resolution": "720p",
        "aspect_ratio": "16:9",
        "seed": -1,
        "generate_audio": True,
        "reference_images": [],
        "reference_videos": [],
        "reference_audios": [],
    },
    param_constraints={
        "duration": {"min": -1, "max": 15, "ui_type": "slider"},
        "resolution": {"enum": ["480p", "720p", "1080p"], "ui_type": "dropdown"},
        "aspect_ratio": {
            "enum": [
                "16:9",
                "4:3",
                "1:1",
                "3:4",
                "9:16",
                "21:9",
                "9:21",
                "adaptive",
            ],
            "ui_type": "dropdown",
        },
        "seed": {"nullable": True},
        "image": {"nullable": True},
        "prompt": {"max": 4000},
    },
    param_help={
        "generate_audio": "Let the model generate matching audio (may cost more).",
        "reference_images": "Style/subject refs. Tag in prompt (e.g. [Image1]).",
        "reference_videos": "Motion/style clips. Prompt tagging usually required.",
        "reference_audios": "Audio refs for sync or style.",
    },
    file_input_params={
        "image": _IMAGE_FILE_TYPES,
        "last_frame_image": _IMAGE_FILE_TYPES,
        "reference_images": _IMAGE_FILE_TYPES,
        "reference_videos": _VIDEO_FILE_TYPES,
        "reference_audios": ["mp3", "wav", "m4a", "aac"],
    },
    high_impact_params=["generate_audio"],
    presets={
        "Fast T2V no audio": {
            "duration": 5,
            "resolution": "720p",
            "generate_audio": False,
        },
        "Balanced": {
            "duration": 5,
            "resolution": "720p",
            "aspect_ratio": "16:9",
            "generate_audio": True,
        },
        "High res + audio": {
            "duration": 8,
            "resolution": "1080p",
            "generate_audio": True,
        },
        "With end frame": {
            "duration": 5,
            "generate_audio": True,
            "last_frame_image": None,  # user still uploads
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/bytedance/seedance-2.0",
    pricing_notes="Approx $0.15/s output; prompt max 4000 chars on Replicate.",
    output_notes="Single video URI; optional image for I2V.",
)

HAPPYHORSE_1_0 = ModelConfig(
    name="happyhorse-1.0",
    display_name="Happy Horse 1.0",
    model_type="video",
    replicate_id="alibaba/happyhorse-1.0",
    supports_text=True,
    supports_image=True,
    provider="replicate",
    provider_model_id="alibaba/happyhorse-1.0",
    provider_endpoint="versionless",
    provider_category="T2V or I2V (Alibaba)",
    provider_summary="Alibaba Happy Horse for text-only or single-image animation with flexible duration (3–15s) and up to 1080p. Simple workflow when you want T2V or a quick start-image animate.",
    strength_tags=["text_to_video", "image_to_video", "flexible_duration", "1080p"],
    workflow_archetype="text_or_image_video",
    workflow_tags=["text_to_video", "image_to_video"],
    generation_modes=[
        ("text", "Text description"),
        ("image", "Animate a start image"),
    ],
    default_generation_mode="text",
    media_roles={
        "prompt": "Prompt",
        "image": "Start frame image",
    },
    balanced_params=["prompt", "duration", "resolution", "aspect_ratio", "seed"],
    advanced_params=[],
    defaults={
        "duration": 5,
        "resolution": "1080p",
        "aspect_ratio": "16:9",
        "seed": -1,
    },
    param_constraints={
        "duration": {
            "enum": [3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15],
            "ui_type": "dropdown",
        },
        "resolution": {"enum": ["720p", "1080p"], "ui_type": "dropdown"},
        "aspect_ratio": {
            "enum": ["16:9", "9:16", "1:1", "4:3", "3:4"],
            "ui_type": "dropdown",
        },
        "seed": {"nullable": True},
        "prompt": {"max": 2500},
        "image": {"nullable": True},
    },
    required_one_of=[("prompt", "image")],
    file_input_params={"image": _IMAGE_FILE_TYPES},
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/alibaba/happyhorse-1.0",
    pricing_notes="720p $0.14/s; 1080p $0.28/s output (Replicate page).",
    output_notes="Single video URI; T2V or I2V from one image.",
)

GEN_4_5 = ModelConfig(
    name="gen-4.5",
    display_name="Runway Gen-4.5",
    model_type="video",
    replicate_id="runwayml/gen-4.5",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="runwayml/gen-4.5",
    provider_endpoint="versionless",
    provider_category="Cinematic T2V / I2V",
    provider_summary="Runway Gen-4.5 — polished cinematic clips from text or a start image. Fixed 5s or 10s durations; strong for production-style motion.",
    strength_tags=["cinematic", "text_to_video", "image_to_video", "runway"],
    workflow_archetype="text_or_image_video",
    workflow_tags=["text_to_video", "image_to_video"],
    media_roles={
        "prompt": "Prompt",
        "image": "Start frame image",
    },
    balanced_params=["prompt", "duration", "aspect_ratio", "seed"],
    advanced_params=[],
    defaults={
        "duration": 5,
        "aspect_ratio": "16:9",
        "seed": None,
    },
    param_constraints={
        "duration": {"enum": [5, 10], "ui_type": "dropdown"},
        "aspect_ratio": {
            "enum": ["16:9", "9:16", "4:3", "3:4", "1:1", "21:9"],
            "ui_type": "dropdown",
        },
        "seed": {"nullable": True},
        "image": {"nullable": True},
    },
    file_input_params={"image": _IMAGE_FILE_TYPES},
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/runwayml/gen-4.5",
    pricing_notes="$0.12/s output (Replicate page).",
    output_notes="Single video URI; duration 5s or 10s only.",
)

SEEDANCE_2_0_FAST = ModelConfig(
    name="seedance-2.0-fast",
    display_name="Seedance 2.0 Fast",
    model_type="video",
    replicate_id="bytedance/seedance-2.0-fast",
    supports_text=True,
    supports_image=True,
    supports_audio=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="bytedance/seedance-2.0-fast",
    provider_endpoint="versionless",
    provider_category="Fast multimodal video",
    provider_summary="Faster, cheaper Seedance variant (480p/720p) with the same multimodal inputs minus 1080p. Use for drafts and iteration.",
    strength_tags=["fast", "multimodal", "cost_efficient", "reference_media"],
    workflow_archetype="multimodal_video",
    workflow_tags=["text_to_video", "image_to_video", "multimodal"],
    media_roles={
        "prompt": "Prompt",
        "image": "Start frame image",
        "last_frame_image": "End frame image",
        "reference_images": "Reference image",
        "reference_videos": "Reference video",
        "reference_audios": "Reference audio",
    },
    balanced_params=[
        "prompt",
        "duration",
        "resolution",
        "aspect_ratio",
        "seed",
        "generate_audio",
    ],
    advanced_params=[],
    defaults={
        "duration": 5,
        "resolution": "720p",
        "aspect_ratio": "16:9",
        "seed": None,
        "generate_audio": True,
        "reference_images": [],
        "reference_videos": [],
        "reference_audios": [],
    },
    param_constraints={
        "duration": {"min": -1, "max": 15, "ui_type": "slider"},
        "resolution": {"enum": ["480p", "720p"], "ui_type": "dropdown"},
        "aspect_ratio": {
            "enum": [
                "16:9",
                "4:3",
                "1:1",
                "3:4",
                "9:16",
                "21:9",
                "9:21",
                "adaptive",
            ],
            "ui_type": "dropdown",
        },
        "seed": {"nullable": True},
        "image": {"nullable": True},
        "last_frame_image": {"nullable": True},
    },
    mutual_exclusion=[
        ("image", "reference_images"),
        ("last_frame_image", "reference_images"),
    ],
    file_input_params={
        "image": _IMAGE_FILE_TYPES,
        "last_frame_image": _IMAGE_FILE_TYPES,
        "reference_images": _IMAGE_FILE_TYPES,
        "reference_videos": _VIDEO_FILE_TYPES,
        "reference_audios": ["mp3", "wav", "m4a", "aac"],
    },
    param_help={
        "generate_audio": "Generate audio track with the video.",
        "reference_images": "Style/subject refs (tag in prompt per model docs).",
    },
    high_impact_params=["generate_audio"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/bytedance/seedance-2.0-fast",
    pricing_notes="$0.07–0.17/s output depending on resolution and video refs.",
    output_notes="Faster Seedance variant; 480p/720p only.",
)

KLING_V3_OMNI = ModelConfig(
    name="kling-v3-omni",
    display_name="Kling 3 Omni Video",
    model_type="video",
    replicate_id="kwaivgi/kling-v3-omni-video",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="kwaivgi/kling-v3-omni-video",
    provider_endpoint="versionless",
    provider_category="Omni multimodal + edit",
    provider_summary="Kling 3 Omni — text, start/end frames, reference images, video edit/reference, optional audio, and 4K mode. Broadest Kling workflow for generate-and-edit.",
    strength_tags=["multimodal", "video_edit", "4k", "reference_video", "audio"],
    workflow_archetype="multimodal_video",
    workflow_tags=["text_to_video", "image_to_video", "edit_video", "multimodal"],
    media_roles={
        "prompt": "Prompt",
        "start_image": "Start frame image",
        "end_image": "End frame image",
        "reference_images": "Reference image",
        "reference_video": "Reference or source video",
    },
    balanced_params=[
        "prompt",
        "mode",
        "duration",
        "aspect_ratio",
        "generate_audio",
    ],
    advanced_params=[
        "video_reference_type",
        "keep_original_sound",
        "multi_prompt",
    ],
    defaults={
        "mode": "pro",
        "duration": 5,
        "aspect_ratio": "16:9",
        "generate_audio": False,
        "keep_original_sound": True,
        "video_reference_type": "feature",
        "multi_prompt": None,
    },
    param_constraints={
        "mode": {"enum": ["standard", "pro", "4k"], "ui_type": "dropdown"},
        "duration": {"min": 3, "max": 15, "ui_type": "slider"},
        "aspect_ratio": {"enum": ["16:9", "9:16", "1:1"], "ui_type": "dropdown"},
        "video_reference_type": {
            "enum": ["feature", "base"],
            "ui_type": "dropdown",
        },
        "prompt": {"max": 2500},
        "start_image": {"nullable": True},
        "end_image": {"nullable": True},
        "reference_video": {"nullable": True},
        "reference_images": {"nullable": True},
        "multi_prompt": {"nullable": True},
    },
    mutual_exclusion=[("generate_audio", "reference_video")],
    file_input_params={
        "start_image": _IMAGE_FILE_TYPES,
        "end_image": _IMAGE_FILE_TYPES,
        "reference_images": _IMAGE_FILE_TYPES,
        "reference_video": _VIDEO_FILE_TYPES,
    },
    param_help={
        "mode": "standard=fast; pro=higher quality; 4k=max res (no ref video).",
        "video_reference_type": "feature=guidance; base=source for edit.",
        "multi_prompt": "Extra structured prompts (see model card).",
        "keep_original_sound": "Preserve audio from reference video.",
    },
    high_impact_params=["mode"],
    presets={
        "Fast / cheap": {
            "mode": "standard",
            "duration": 5,
            "generate_audio": False,
            "video_reference_type": "feature",
        },
        "Balanced pro": {
            "mode": "pro",
            "duration": 5,
            "aspect_ratio": "16:9",
            "generate_audio": False,
        },
        "High quality + audio": {
            "mode": "pro",
            "duration": 8,
            "generate_audio": True,
            "keep_original_sound": False,
        },
        "4K cinematic": {
            "mode": "4k",
            "duration": 5,
            "aspect_ratio": "16:9",
            "generate_audio": False,
        },
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/kwaivgi/kling-v3-omni-video",
    pricing_notes="$0.168–$0.42/s output by mode and audio (Replicate page).",
    output_notes="Multimodal T2V/I2V/edit; 4k mode excludes reference video.",
)

DREAMACTOR_M2_0 = ModelConfig(
    name="dreamactor-m2.0",
    display_name="Dreamactor M2.0",
    model_type="video",
    replicate_id="bytedance/dreamactor-m2.0",
    supports_text=False,
    supports_image=True,
    requires_image=True,
    provider="replicate",
    provider_model_id="bytedance/dreamactor-m2.0",
    provider_endpoint="versionless",
    provider_category="Character motion transfer",
    provider_summary="Apply motion from a driving video onto a character still image. No prompt required — image plus motion clip in, animated character out.",
    strength_tags=["motion_transfer", "character", "driving_video"],
    workflow_archetype="motion_transfer",
    workflow_tags=["motion_transfer"],
    media_roles={
        "image": "Character image",
        "video": "Driving video",
    },
    balanced_params=["cut_first_second"],
    advanced_params=[],
    defaults={"cut_first_second": True},
    param_constraints={
        "cut_first_second": {"ui_type": "checkbox"},
    },
    file_input_params={
        "image": ["png", "jpg", "jpeg"],
        "video": _VIDEO_FILE_TYPES,
    },
    required_file_params=["image", "video"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/bytedance/dreamactor-m2.0",
    pricing_notes="$0.05/s output (Replicate page).",
    output_notes="Motion from driving video applied to character image.",
)

ALEPH_2 = ModelConfig(
    name="aleph-2",
    display_name="Runway Aleph 2.0",
    model_type="video",
    replicate_id="runwayml/aleph-2",
    supports_text=True,
    supports_image=False,
    requires_text=True,
    provider="replicate",
    provider_model_id="runwayml/aleph-2",
    provider_endpoint="versionless",
    provider_category="Video editing (Runway)",
    provider_summary="Runway Aleph 2 — edit an uploaded clip (2–30s) with natural-language instructions. Early-access video-to-video refinement.",
    strength_tags=["video_edit", "instructional", "runway"],
    workflow_archetype="video_edit",
    workflow_tags=["edit_video"],
    media_roles={
        "prompt": "Edit instructions",
        "video": "Source video",
    },
    balanced_params=["prompt", "seed"],
    advanced_params=[],
    defaults={"seed": None},
    param_constraints={
        "seed": {"nullable": True},
    },
    file_input_params={"video": _VIDEO_FILE_TYPES},
    required_file_params=["video"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/runwayml/aleph-2",
    pricing_notes="$0.336/s output; early-access model (Replicate page).",
    output_notes="Edit uploaded clip (2–30s, ≤16MB); keyframes deferred in UI.",
)

KLING_V3_MOTION = ModelConfig(
    name="kling-v3-motion",
    display_name="Kling 3 Motion Control",
    model_type="video",
    replicate_id="kwaivgi/kling-v3-motion-control",
    supports_text=True,
    supports_image=True,
    requires_image=True,
    provider="replicate",
    provider_model_id="kwaivgi/kling-v3-motion-control",
    provider_endpoint="versionless",
    provider_category="Motion control (Kling)",
    provider_summary="Transfer motion from a reference video onto a character image with std/pro quality tiers and optional prompt guidance.",
    strength_tags=["motion_transfer", "character", "quality_tiers"],
    workflow_archetype="motion_transfer",
    workflow_tags=["motion_transfer"],
    media_roles={
        "image": "Character image",
        "video": "Driving video",
        "prompt": "Optional prompt",
    },
    balanced_params=["mode", "character_orientation", "keep_original_sound"],
    advanced_params=["prompt"],
    defaults={
        "mode": "pro",
        "character_orientation": "image",
        "keep_original_sound": True,
        "prompt": "",
    },
    param_constraints={
        "mode": {"enum": ["std", "pro"], "ui_type": "dropdown"},
        "character_orientation": {
            "enum": ["image", "video"],
            "ui_type": "dropdown",
        },
    },
    file_input_params={
        "image": _IMAGE_FILE_TYPES,
        "video": _VIDEO_FILE_TYPES,
    },
    required_file_params=["image", "video"],
    param_help={
        "mode": "pro usually better motion quality.",
        "character_orientation": "Driving video or character image sets facing.",
        "keep_original_sound": "Preserve audio from driving video.",
    },
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/kwaivgi/kling-v3-motion-control",
    pricing_notes="$0.07/s (std), $0.12/s (pro) output.",
    output_notes="Transfer motion from reference video to character image.",
)

KLING_O1 = ModelConfig(
    name="kling-o1",
    display_name="Kling O1",
    model_type="video",
    replicate_id="kwaivgi/kling-o1",
    supports_text=True,
    supports_image=True,
    requires_text=True,
    provider="replicate",
    provider_model_id="kwaivgi/kling-o1",
    provider_endpoint="versionless",
    provider_category="NL video edit + generate",
    provider_summary="Kling O1 for multimodal generation or editing via reference video (feature vs base modes). Lighter cousin to Omni without a 4K tier.",
    strength_tags=["multimodal", "video_edit", "reference_video"],
    workflow_archetype="multimodal_video",
    workflow_tags=["text_to_video", "image_to_video", "edit_video", "multimodal"],
    media_roles={
        "prompt": "Prompt",
        "start_image": "Start frame image",
        "end_image": "End frame image",
        "reference_images": "Reference image",
        "reference_video": "Reference or source video",
    },
    balanced_params=[
        "prompt",
        "mode",
        "duration",
        "aspect_ratio",
        "video_reference_type",
    ],
    advanced_params=[
        "keep_original_sound",
    ],
    defaults={
        "mode": "pro",
        "duration": 5,
        "aspect_ratio": "16:9",
        "video_reference_type": "feature",
        "keep_original_sound": True,
    },
    param_constraints={
        "mode": {"enum": ["std", "pro"], "ui_type": "dropdown"},
        "duration": {"enum": [3, 4, 5, 6, 7, 8, 9, 10], "ui_type": "dropdown"},
        "aspect_ratio": {"enum": ["16:9", "9:16", "1:1"], "ui_type": "dropdown"},
        "video_reference_type": {
            "enum": ["feature", "base"],
            "ui_type": "dropdown",
        },
        "start_image": {"nullable": True},
        "end_image": {"nullable": True},
        "reference_video": {"nullable": True},
        "reference_images": {"nullable": True},
    },
    file_input_params={
        "start_image": _IMAGE_FILE_TYPES,
        "end_image": _IMAGE_FILE_TYPES,
        "reference_images": _IMAGE_FILE_TYPES,
        "reference_video": _VIDEO_FILE_TYPES,
    },
    param_help={
        "mode": "std vs pro quality tier.",
        "video_reference_type": "feature=guidance; base=edit source video.",
    },
    high_impact_params=["mode"],
    metadata_verified_date="2026-06-04",
    replicate_page_url="https://replicate.com/kwaivgi/kling-o1",
    pricing_notes="$0.084–$0.168/s output by mode and video input.",
    output_notes="NL video edit or multimodal generation via reference_video type.",
)

VIDEO_MODELS: list[ModelConfig] = [
    WAN_2_7_T2V,
    WAN_2_5_I2V,
    SEEDANCE_2_0,
    HAPPYHORSE_1_0,
    GEN_4_5,
    SEEDANCE_2_0_FAST,
    KLING_V3_OMNI,
    DREAMACTOR_M2_0,
    ALEPH_2,
    KLING_V3_MOTION,
    KLING_O1,
]
